### PR TITLE
ref type support

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by beef331** [comment]
No test, and no usage example.

**Comment by beef331** [comment]
Sorry I also just remembered that this uses `init` constructors, so the ref constructors should use `new`.

**Comment by bung87** [comment]
so in this case we dont need generate in it proc , right?

**Comment by beef331** [comment]
We need a `proc new(_: typedesc Line, ...)` instead of `init` for each variant of the object.

**Pull request closed without merging**
